export const moedas = [
    { nome: 'Real Brasileiro', value: 'BRL', bandeira: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/205.png' }, { nome: 'Dólar Americano', value: 'USD', bandeira: 'https://s3.static.brasilescola.uol.com.br/be/conteudo/images/estados-unidos.jpg' }, { nome: 'Peso Uruguaio', value: 'UYU', bandeira: 'https://www.worldometers.info//img/flags/small/tn_uy-flag.gif' },
    { nome: 'Peso Argentino', value: 'ARS', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ar-flag.gif' }, { nome: 'Dólar Canadense', value: 'CAD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ca-flag.gif' }, { nome: 'Peso Chileno', value: 'CLP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ci-flag.gif' },
    { nome: 'Peso Colombiano', value: 'COP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_co-flag.gif' }, { nome: 'Peso Cubano', value: 'CUP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_cu-flag.gif' }, { nome: 'Libra Esterlina', value: 'GBP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_uk-flag.gif' },
    { nome: 'Iene Japonês', value: 'JPY', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ja-flag.gif' }, { nome: 'Dólar Jamaicano', value: 'JMD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_jm-flag.gif' }, { nome: 'Franco Suíço', value: 'CHF', bandeira: 'https://www.worldometers.info//img/flags/small/tn_sz-flag.gif' },
    { nome: 'Euro', value: 'EUR', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg' }, { nome: 'Libra Egípcia', value: 'EGP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_eg-flag.gif' }, { nome: 'Yuan Chinês', value: 'CNY', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ch-flag.gif' },
    { nome: 'Rublo Russo', value: 'RUB', bandeira: 'https://www.worldometers.info//img/flags/small/tn_rs-flag.gif' }, { nome: 'Dólar Australiano', value: 'AUD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_as-flag.gif' }, { nome: 'Kwanza Angolano', value: 'AOA', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ao-flag.gif' },
    { nome: 'Dinar Argelino', value: 'DZD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ag-flag.gif' }, { nome: 'Peso Dominicano', value: 'DOP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_dr-flag.gif' }, { nome: 'Coroa Dinamarquesa', value: 'DKK', bandeira: 'https://www.worldometers.info//img/flags/small/tn_da-flag.gif' }, 
    { nome: 'Dólar de Fiji', value: 'FJD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_fj-flag.gif' }, { nome: 'Lari Georgiano', value: 'GEL', bandeira: 'https://www.worldometers.info//img/flags/small/tn_gg-flag.gif' }, { nome: 'Cedi Ganês', value: 'GHS', bandeira: 'https://www.worldometers.info//img/flags/small/tn_gh-flag.gif' },
    { nome: 'Coroa Checa', value: 'CZK', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ez-flag.gif' }, { nome: 'Dólar de Belize', value: 'BZD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bh-flag.gif' }, { nome: 'Rublo Bielorrusso', value: 'BYN', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bo-flag.gif' },
    { nome: 'Dólar das Bahamas', value: 'BSD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bf-flag.gif' }, { nome: 'Boliviano', value: 'BOB', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bl-flag.gif' }, { nome: 'Dólar de Brunei', value: 'BND', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bx-flag.gif' },
    { nome: 'Dólar de Barbados', value: 'BBD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bb-flag.gif' }, { nome: 'Dirham dos Emirados', value: 'AED', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ae-flag.gif' }, { nome: 'Dinar Kuwaitiano', value: 'KWD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ku-flag.gif' },
    { nome: 'Won Sul-Coreano', value: 'KRW', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ks-flag.gif' }, { nome: 'Dólar de Trinidad', value: 'TTD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_td-flag.gif' }, { nome: 'Dinar Tunisiano', value: 'TND', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ts-flag.gif' },
    { nome: 'Nova Lira Turca', value: 'TRY', bandeira: 'https://www.worldometers.info//img/flags/small/tn_tu-flag.gif' }, { nome: 'Bolívar Venezuelano', value: 'VES', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ve-flag.gif' }, { nome: 'Hryvnia ucraniano', value: 'UAH', bandeira: 'https://www.worldometers.info//img/flags/small/tn_up-flag.gif' },
    { nome: 'Dólar do Caribe Oriental', value: 'XCD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Flag_of_Eastern_Caribean.png/220px-Flag_of_Eastern_Caribean.png' }, { nome: 'Taka de Bangladesh', value: 'BDT', bandeira: 'https://www.worldometers.info//img/flags/small/tn_bg-flag.gif' }, { nome: 'Rand Sul-Africano', value: 'ZAR', bandeira: 'https://www.worldometers.info//img/flags/small/tn_sf-flag.gif' },
    { nome: 'Dólar Zimbabuense', value: 'ZWL', bandeira: 'https://www.worldometers.info//img/flags/small/tn_zi-flag.gif' }, { nome: 'Riyal Iemenita', value: 'YER', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ym-flag.gif' }, { nome: 'Dólar Taiwanês', value: 'TWD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/1200px-Flag_of_the_Republic_of_China.svg.png' },
    { nome: 'Libra Síria', value: 'SYP', bandeira: 'https://www.worldometers.info//img/flags/small/tn_sy-flag.gif' }, { nome: 'Dólar de Cingapura', value: 'SGD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_sn-flag.gif' }, { nome: 'Coroa Sueca', value: 'SEK', bandeira: 'https://www.worldometers.info//img/flags/small/tn_sw-flag.gif' },
    { nome: 'Dinar do Bahrein', value: 'BHD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ba-flag.gif' }, { nome: 'Dólar Neozelandês', value: 'NZD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_nz-flag.gif' }, { nome: 'Dólar de Hong Kong', value: 'HKD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/1200px-Flag_of_Hong_Kong.svg.png' },
    { nome: 'Franco da Guiné', value: 'GNF', bandeira: 'https://www.worldometers.info//img/flags/small/tn_gv-flag.gif' }, { nome: 'Rupia indonésia', value: 'IDR', bandeira: 'https://www.worldometers.info//img/flags/small/tn_id-flag.gif' }, { nome: 'Dólar das Ilhas Cayman', value: 'KYD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/640px-Flag_of_the_Cayman_Islands.svg.png' },
    { nome: 'Tenge', value: 'KZT', bandeira: 'https://www.worldometers.info//img/flags/small/tn_kz-flag.gif' }, { nome: 'Kip', value: 'LAK', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/1200px-Flag_of_Laos.svg.png' }, { nome: 'Rupia do Sri Lanka', value: 'LKR', bandeira: 'https://www.worldometers.info//img/flags/small/tn_ce-flag.gif' },
    { nome: 'Dólar liberiano', value: 'LRD', bandeira: 'https://www.worldometers.info//img/flags/small/tn_li-flag.gif' }, { nome: 'Dinar líbio', value: 'LYD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/1200px-Flag_of_Libya.svg.png' }, { nome: 'Dirham marroquino', value: 'MAD', bandeira: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/255px-Flag_of_Morocco.svg.png' },
]


export async function request(args){
    const response = await fetch(`https://v6.exchangerate-api.com/v6/ce531db59bbf57d7f539f7fd/latest/${args}`)
    const data = await response.json()
    return data.result == 'success' ? data : alert("Erro: " + data["error-type"])
}